### ISSUE TITLE
[ADD] 튜토리얼 - 평가 구조 설계

### ISSUE THREAD

**Issue by Guel-git** [GordonRamjo/BurgerBuilder#19]
## Issue
튜토리얼 씬에서 사용될 평가 구조를 설계합니다.

## TODO
- [x] 트레이 배치 (불러오기)
- [x] id 설정 (재료별로)
- [x] 정답 array 생성
- [x] 콜라이드 & 재료 놓으면 -> 비교 후 일치하면 -> ingredient num ++
