### ISSUE TITLE
[Feature] Sound 설정

### ISSUE THREAD

**Issue by yourzinc** [GordonRamjo/BurgerBuilder#22]
## Issue
- 기본 BGM 을 설정한다
- 진상 손님이 등장할 경우 BGM 을 전환한다
- 패티를 구울 때 효과음을 추가한다
- 물건을 잡거나, 둘 때, 쓰레기통에 버릴 때 효과음을 추가한다

## TODO
- [x] 기본 BGM 설정
- [x] 진상 손님 BGM 설정
- [x] 패티 굽기 적용 
- [x] Grab, Drop 적용 
- [x] 쓰레기통 적용
- [ ] 걷는 소리 적용
