### ISSUE TITLE
[ADD] 튜토리얼 - 엔딩 구현

### ISSUE THREAD

**Issue by Guel-git** [GordonRamjo/BurgerBuilder#34]
## Contents
튜토리얼이 끝나면 나오는 엔딩을 구현합니다.

## TODO
- [x] Ending Canvas 생성
- [x] 이미지 추가
- [x] 사운드 추가
- [x] dialog 추가
- [x] dialog manager script 추가
- [x] guide -> ending 연결
- [x] ending -> stage manger 연결
