### ISSUE TITLE
[ADD] 튜토리얼 - Intro 구현

### ISSUE THREAD

**Issue by Guel-git** [GordonRamjo/BurgerBuilder#5]
## Issue
- scene 초기 세팅을 하고, 튜토리얼의 인트로를 구현합니다.

## TODO
- [x] 씬 생성 및 초기 세팅
- [x] 인트로 UI 구성
- [x] 인트로 script 구성
- [x] 인트로 action 넣기 (마우스 클릭하면 다음 화면으로 이동)
