### ISSUE TITLE
[ADD] 튜토리얼 - Guide 구현

### ISSUE THREAD

**Issue by Guel-git** [GordonRamjo/BurgerBuilder#7]
## Issue
- 튜토리얼 Guide 기능을 구현합니다.
- 결과 버거를 보여주고, 아래 빵 -> 재료들 하나하나 -> 위에 빵 순서대로 가이드를 제공할 예정입니다.
- 재료들이 제대로 조리되고 올라갔는지 확인해야 하는데 이번 이슈에서는 space 누르면 dialog 넘어가는 것만 구현할 예정입니다.

## TODO
- [x] GuideCanvas 생성
- [x] 재료들 이미지 캡처 후 추가
- [x] 인트로 종료 후 Guide hidden 처리 제거
- [x] 스페이스 누를 때마다 다른 script랑 재료 이미지 보여주기
